DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'news_category') THEN
        CREATE TYPE news_category AS ENUM ('TECH', 'PROMOTION', 'GUIDE', 'NEWS');
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS news (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title           VARCHAR(255) NOT NULL DEFAULT '',
    slug            VARCHAR(280) NOT NULL DEFAULT '',
    excerpt         TEXT,
    content         TEXT NOT NULL DEFAULT '',
    thumbnail       TEXT,
    category        news_category NOT NULL DEFAULT 'NEWS',
    author_id       UUID REFERENCES profiles(id) ON DELETE SET NULL,
    is_published    BOOLEAN NOT NULL DEFAULT FALSE,
    published_at    TIMESTAMP,
    view_count      INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE news ADD COLUMN IF NOT EXISTS title VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE news ADD COLUMN IF NOT EXISTS slug VARCHAR(280);
ALTER TABLE news ADD COLUMN IF NOT EXISTS excerpt TEXT;
ALTER TABLE news ADD COLUMN IF NOT EXISTS content TEXT NOT NULL DEFAULT '';
ALTER TABLE news ADD COLUMN IF NOT EXISTS thumbnail TEXT;
ALTER TABLE news ADD COLUMN IF NOT EXISTS category news_category NOT NULL DEFAULT 'NEWS';
ALTER TABLE news ADD COLUMN IF NOT EXISTS author_id UUID REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE news ADD COLUMN IF NOT EXISTS is_published BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE news ADD COLUMN IF NOT EXISTS published_at TIMESTAMP;
ALTER TABLE news ADD COLUMN IF NOT EXISTS view_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE news ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE news ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_news_published ON news(is_published, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_news_slug ON news(slug);
CREATE INDEX IF NOT EXISTS idx_news_category ON news(category);
